#!/bin/ash

cryptname="${1}"

# Start udev from initramfs
/lib/systemd/systemd-udevd --daemon --resolve-names=never

# Sync one more time, just in case
sync

# Suspend root device
[ -z "${cryptname}" ] || cryptsetup luksSuspend "${cryptname}"

# Suspend the system
echo mem > /sys/power/state

# Resume root device
[ -z "${cryptname}" ] ||
    while true; do
        cryptsetup luksResume "${cryptname}"
        [[ $? == 0 ]] && break
        [[ $? == 1 ]] && break
        sleep 2
    done

# Stop udev from initramfs, as the real daemon from rootfs will be restarted
udevadm control --exit
